import './globals.css';

export const metadata = {
  title: 'Blog JM',
  description: 'Generated by JM',
};

export default function RootLayout({ children }) {
  return (
    <html lang='ko'>
      <body>
        <div className='flex min-h-screen flex-col items-center justify-between p-24'>
          <header>Header</header>
          {children}
          <footer>Footer</footer>
        </div>
      </body>
    </html>
  );
}
